### ISSUE TITLE
missing exposed filter styles

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#12]
could be better integrated to match button styles
![screen shot 2014-03-26 at 3 49 29 pm](https://cloud.githubusercontent.com/assets/1919260/2531945/f351bfb4-b538-11e3-9ffd-f7ee2bbda1ed.png)

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/134
