### ISSUE TITLE
image border styles in wells need tweaking

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#41]
the border color is the same as the well color... need to change it or remove it.
![screen shot 2014-10-27 at 3 12 07 pm](https://cloud.githubusercontent.com/assets/1919260/4800463/6266acf2-5e26-11e4-91ef-e2c64378c256.png)

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/123
