### ISSUE TITLE
Sidebar menu nested link color contrast in Bright and Contrast styles

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#52]
![screen shot 2014-11-24 at 2 33 54 pm](https://cloud.githubusercontent.com/assets/1919260/5174546/f3e53b50-73e6-11e4-8f43-ba4a6ca3eb21.png)
![screen shot 2014-11-24 at 2 35 18 pm](https://cloud.githubusercontent.com/assets/1919260/5174572/28ad1100-73e7-11e4-8641-f7f3e7a935ed.png)

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/122
