### ISSUE TITLE
IE8 blockquote doesn't have a background color

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#56]
![screen shot 2014-11-24 at 2 46 34 pm](https://cloud.githubusercontent.com/assets/1919260/5174746/b6c66c4c-73e8-11e4-9bc5-2e97ee1ff776.png)

and :before :after quotes are small... not high priority. and no :after quote for some reason.

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/118
