### ISSUE TITLE
Caret dropdown is wrong color on hover/active/open

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#58]
Rich:
![screen shot 2014-11-24 at 8 18 12 pm](https://cloud.githubusercontent.com/assets/1919260/5177936/0f8cbe34-7417-11e4-9b28-9111fe98ef7e.png)

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/116
