### ISSUE TITLE
Rich & Bright & Dark links in wells don't have enough contrast

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_light#64]
![screen shot 2014-11-24 at 8 55 04 pm](https://cloud.githubusercontent.com/assets/1919260/5178187/3be7a3ea-741c-11e4-922a-88acbfed201b.png)
![screen shot 2014-11-24 at 8 55 07 pm](https://cloud.githubusercontent.com/assets/1919260/5178188/3c11dc32-741c-11e4-914a-49421aac1e34.png)

![screen shot 2014-11-24 at 8 57 13 pm](https://cloud.githubusercontent.com/assets/1919260/5178201/790f1352-741c-11e4-85bd-0c75d8a238af.png)

![screen shot 2014-11-24 at 8 58 25 pm](https://cloud.githubusercontent.com/assets/1919260/5178209/a408945c-741c-11e4-91f2-ae5d65c59953.png)

**Comment by hyperboy** [comment]
Migrated to https://github.com/SU-SWS/stanford_framework/issues/113
